---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: mysql
  volumeMode: Filesystem

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql
  namespace: default
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-control-plane
  hostPath:
    path: /srv/mysql
    type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeName: kind-control-plane
      # volumes:
      #   - name: mysql
      #     emptyDir:
      #       sizeLimit: 500Mi
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql
      containers:
      - name: mysql
        image: mysql:8-oracle
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "passw0rd"
        - name: MYSQL_DATABASE
          value: "airflow"
        - name: MYSQL_USER
          value: "airflow"
        - name: MYSQL_PASSWORD
          value: "airflow"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306